name: "If Example"
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This step always runs"
      - if: ${{ github.event_name == 'push' }}
        run: echo "This step runs only on push events"
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: echo "This step runs only if the actor is dependabot[bot]"
      - if: ${{ github.event_name != 'pull_request' }}
        run: echo "This step runs only if the event is not a pull request"
